# Site settings
title: Welcome Visitor !
email: shvamverma@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is designed to help developers go through basic details of the development
  process.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: shvamverma
github_username:  shivamv

# Build settings
markdown: kramdown
